plugins {
    id 'java'
    id 'application'
    id 'org.beryx.jlink' version '3.0.1'
    id 'org.openjfx.javafxplugin' version '0.0.13'
    id 'org.springframework.boot' version '2.7.18'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.github.desktop'
version = '1.0.0'

def platformClassifier
def osName = System.getProperty('os.name').toLowerCase()
def osArch = System.getProperty('os.arch').toLowerCase()
if (osName.contains('mac')) {
    if (osArch.contains('aarch64')) {
        platformClassifier = 'mac-aarch64'
    } else {
        platformClassifier = 'mac'
    }
} else if (osName.contains('windows')) {
    platformClassifier = 'win'
} else if (osName.contains('linux')) {
    platformClassifier = 'linux'
}

application {
    mainModule = 'com.github.desktop'
    mainClass = 'com.github.desktop.SpringLunchApplication'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

javafx {
    version = '17.0.12'
    modules = ['javafx.controls', 'javafx.fxml', 'javafx.web']
}

repositories {
    mavenCentral()
    maven {
        name = "JxBrowser"
        url 'https://europe-maven.pkg.dev/jxbrowser/releases'
        name = 'com.teamdev'
    }
}

dependencies {
    // Web MVC
    implementation("org.springframework.boot:spring-boot-starter-web") {
        exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
    }

    // Logging
    implementation 'org.springframework.boot:spring-boot-starter-log4j2'

    // SpringBoot JavaFX
    implementation 'net.rgielen:javafx-weaver-spring-boot-starter:1.3.0'

    // JX Browser
    implementation 'com.teamdev.jxbrowser:jxbrowser-cross-platform:8.2.1'
    implementation 'com.teamdev.jxbrowser:jxbrowser-javafx:8.2.1'

    // JavaFX dependencies explicitly
    implementation "org.openjfx:javafx-base:${javafx.version}:${platformClassifier}"
    implementation "org.openjfx:javafx-graphics:${javafx.version}:${platformClassifier}"
    implementation "org.openjfx:javafx-controls:${javafx.version}:${platformClassifier}"
    implementation "org.openjfx:javafx-fxml:${javafx.version}:${platformClassifier}"
    implementation "org.openjfx:javafx-web:${javafx.version}:${platformClassifier}"

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    implementation 'org.projectlombok:lombok'

    // Test
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}

jlink {
    imageZip = project.file("${layout.buildDirectory}/distributions/app-${javafx.platform.classifier}.zip")
    options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
    launcher {
        name = 'javafx-jxbrowser-demo-app'
    }

    forceMerge "log4j-api"

    addExtraDependencies("javafx.base", "javafx.graphics", "javafx.controls", "javafx.fxml")

    mergedModule {
        requires 'java.desktop'
        requires 'java.logging'

        uses 'org.springframework.boot.autoconfigure.AutoConfigurationImportFilter'
        uses 'org.springframework.boot.autoconfigure.AutoConfigurationImportListener'
        uses 'org.springframework.boot.autoconfigure.EnableAutoConfiguration'
    }
}

jlinkZip {
    group = 'distribution'
}